name: CI

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.3

      - run: ./scripts/check.sh --no-docker

      - run: ./scripts/build.sh --no-docker 0.1.0
