name: Release to npm

on:
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.3

      - run: ./scripts/check.sh --no-docker

      - run: ./scripts/build.sh --no-docker "$(basename "${GITHUB_REF}" | cut -c2-)"

      - run: npm publish --access public
        working-directory: ./npm 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
